apiVersion: apps/v1                                                                
kind: Deployment                                                                   
metadata:                                                                            
    name: website                                                                      
    labels:                                                                              
        app: website                                                                   
spec:                                                                                
    replicas: 3                                                                        
    selector:                                                                            
        matchLabels:                                                                         
            app: website                                                                   
    template:                                                                            
        metadata:                                                                            
            labels:                                                                              
                app: website                                                                   
        spec:                                                                                
            containers:                                                                        
            - name: website                                                                          
              image: malikbilalali1/website:0.1                                                  
              ports:                                                                             
              - containerPort: 80                                                                                                                                               
---                                                                                                                                                                   
apiVersion: v1                                                                     
kind: Service                                                                      
metadata:                                                                            
    name: web-svc                                                                    
spec:                                                                                
    selector:                                                                            
        app: website                                                                     
    ports:                                                                               
    - port: 80                                                                           
      targetPort: 80                                                                     
      nodePort: 31001                                                                
    type: NodePort 